apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: anonranger/learnk8-worker-service:latest
        ports:
        - containerPort: 80
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/learn_k8"
        - name: PORT
          value: ":80"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP